<?php
namespace Database\Seeders;

use App\Models\Calificacion;
use Illuminate\Database\Seeder;

class CalificacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $materias_docente =
        [
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '1','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '2','docente_id' => '3','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '3','docente_id' => '4','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '4','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '5','docente_id' => '6','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '6','docente_id' => '7','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '7','docente_id' => '8','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '8','docente_id' => '9','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '9','docente_id' => '10','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '10','docente_id' => '11','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '11','docente_id' => '12','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '12','docente_id' => '2','postgrado_id' => '1','postgraduante_id' => '15',],

        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '1',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '2',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '3',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '4',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '5',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '6',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '7',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '8',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '9',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '10',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '11',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '12',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '13',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '14',],
        ['nota_numerica' => '98','nota_literal' => 'NOVENTA Y OCHO','observacion' => 'Nada..','fecha_registro' => '2021-03-28 23:08:13','materia_id' => '13','docente_id' => '5','postgrado_id' => '1','postgraduante_id' => '15',],


        ];
        foreach ($materias_docente as $asignacion) {
            Calificacion::create($asignacion);
        }
    }
}
